//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YKT.Exam.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseTestPaper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaseTestPaper()
        {
            this.TestPaper = new HashSet<TestPaper>();
            this.PaperQuestion = new HashSet<PaperQuestion>();
        }
    
        public int Id { get; set; }
        public string BaseTestPaperName { get; set; }
        public Nullable<System.DateTime> BaseTestPaperCreateTime { get; set; }
        public string BaseTestPaperType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestPaper> TestPaper { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaperQuestion> PaperQuestion { get; set; }
    }
}
