//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YKT.Exam.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TestQuestion> TestQuestionSet { get; set; }
        public virtual DbSet<TestPaper> TestPaperSet { get; set; }
        public virtual DbSet<Teacher> TeacherSet { get; set; }
        public virtual DbSet<Student> StudentSet { get; set; }
        public virtual DbSet<Course> CourseSet { get; set; }
        public virtual DbSet<Score> ScoreSet { get; set; }
        public virtual DbSet<Class> ClassSet { get; set; }
        public virtual DbSet<Comment> CommentSet { get; set; }
        public virtual DbSet<Collection> CollectionSet { get; set; }
        public virtual DbSet<StudentTestResult> StudentTestResultSet { get; set; }
        public virtual DbSet<PaperQuestion> PaperQuestionSet { get; set; }
        public virtual DbSet<BaseTestPaper> BaseTestPaperSet { get; set; }
    }
}
