//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YKT.Exam.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestPaper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestPaper()
        {
            this.StudentTestResult = new HashSet<StudentTestResult>();
            this.Score = new HashSet<Score>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> TestPaperStartTime { get; set; }
        public Nullable<System.DateTime> TestPaperEndTime { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentTestResult> StudentTestResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Score> Score { get; set; }
        public virtual BaseTestPaper BaseTestPaper { get; set; }
    }
}
